spring.application.name=sistema-interiorismo
spring.datasource.url=jdbc:mysql://localhost:3306/interiorismo
spring.datasource.username=root
<<<<<<< HEAD
spring.datasource.password=teamo1452
=======
spring.datasource.password=Firefly
>>>>>>> master

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
